name: Gradle Assemble
on: [pull_request]

jobs:
  assemble:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ${{ matrix.os }}
    permissions:
      pull-requests: write # this allows to show table and charts in PRs
    strategy:
      matrix:
        java: [ 11, 17, 21 ]
        os: [ubuntu-latest, windows-latest, macos-13]
    steps:
      - name: Eco CI Energy Estimation - Initialize
        if: matrix.os == 'ubuntu-latest'
        uses: green-coding-solutions/eco-ci-energy-estimation@v4.0-rc3
        with:
          task: start-measurement

      - uses: actions/checkout@v4

      - name: Eco CI Energy Estimation - Get Measurement
        if: matrix.os == 'ubuntu-latest'
        uses: green-coding-solutions/eco-ci-energy-estimation@v4.0-rc3
        with:
          task: get-measurement
          label: 'checkout'


      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Eco CI Energy Estimation - Get Measurement
        if: matrix.os == 'ubuntu-latest'
        uses: green-coding-solutions/eco-ci-energy-estimation@v4.0-rc3
        with:
          task: get-measurement
          label: 'set up JDK'


      - name: Setup docker (missing on MacOS)
        id: setup_docker
        if: runner.os == 'macos'
        uses: douglascamata/setup-docker-macos-action@main
        continue-on-error: true
        with:
          upgrade-qemu: true
          colima:  v0.6.8

      - name: Run Gradle (assemble)
        if: runner.os == 'macos' && steps.setup_docker.outcome != 'success'
        run: |
          # Report success even if previous step failed (Docker on MacOS runner is very unstable)
          exit 0;
      - name: Run Gradle (assemble)
        if: runner.os != 'macos'
        run: |
          ./gradlew assemble --parallel --no-build-cache -PDISABLE_BUILD_CACHE

      - name: Run Gradle (assemble)
        if: runner.os == 'macos' && steps.setup_docker.outcome == 'success'
        run: |
          ./gradlew assemble --parallel --no-build-cache -PDISABLE_BUILD_CACHE

      - name: Eco CI Energy Estimation - Get Measurement
        if: matrix.os == 'ubuntu-latest'
        uses: green-coding-solutions/eco-ci-energy-estimation@v4.0-rc3
        with:
          task: get-measurement
          label: 'gradlew assemble'

      - name: Eco CI Energy Estimation - End Measurement
        if: matrix.os == 'ubuntu-latest'
        uses: green-coding-solutions/eco-ci-energy-estimation@v4.0-rc3
        with:
          task: display-results
          send-data: true
